### ISSUE TITLE
Uploading Of Supporting Documents In Pull Requests Guides

### ISSUE THREAD

**Issue by Jamesong7822** [OpenSUTD/fifth-row-guides#18]
Hi, 

Just wandering what the procedure is like for uploading or attaching of supporting documents in our guides we submit in pull requests. 
Please advise.

Thanks!

**Comment by piroton** [comment]
Officially now, supporting documents like images embedded within guides should be named in the following format:

`assets/document-name/asset-type`.

Thank you for the contribution. I will upload a CONTRIBUTING.md file to update all users on how to add to the repository properly.
